language: node_js

node_js:
  - 6

notifications:
  email:
    recipients:
      - shane@shanetomlinson.com
    on_success: change
    on_failure: always

before_install:
  - npm install -g grunt-cli

script:
  - npm run nsp
  - grunt jshint
  - npm test
